// models/AgentBooking.model.ts
import mongoose, { Document, Schema } from 'mongoose';

export interface IAgentBooking extends Document {
  // Trip reference — points to AgentTrip, NOT the public Trip model
  agentTripId: mongoose.Types.ObjectId;
  tripName: string;

  // Agent who made the booking
  agentId?: mongoose.Types.ObjectId;
  agentName?: string;
  agentEmail?: string;
  agentCompany?: string;

  // Customer (the agent's client)
  customerName: string;
  email: string;
  phone: string;
  message?: string;

  // Booking details
  travelers: number;
  selectedDate?: string;
  occupancyType?: string;       // e.g. "Triple Sharing", "Double Sharing"
  selectedPrice?: number;       // B2B price per person
  totalAmount: number;          // B2B total

  // Status
  status: 'Pending' | 'Confirmed' | 'Cancelled';
  bookingId: string;            // e.g. AB000001

  createdAt: Date;
  updatedAt: Date;
}

const agentBookingSchema = new Schema<IAgentBooking>(
  {
    agentTripId: {
      type: Schema.Types.ObjectId,
      ref: 'AgentTrip',
      required: [true, 'Agent Trip ID is required'],
    },
    tripName: {
      type: String,
      required: [true, 'Trip name is required'],
      trim: true,
    },
    agentId: {
      type: Schema.Types.ObjectId,
      ref: 'Agent',
    },
    agentName: { type: String, trim: true },
    agentEmail: { type: String, trim: true, lowercase: true },
    agentCompany: { type: String, trim: true },

    customerName: {
      type: String,
      required: [true, 'Customer name is required'],
      trim: true,
    },
    email: {
      type: String,
      required: [true, 'Email is required'],
      trim: true,
      lowercase: true,
    },
    phone: {
      type: String,
      required: [true, 'Phone number is required'],
      trim: true,
    },
    message: { type: String, trim: true },

    travelers: {
      type: Number,
      required: [true, 'Number of travelers is required'],
      min: [1, 'At least 1 traveler is required'],
    },
    selectedDate: { type: String, trim: true },
    occupancyType: { type: String, trim: true },
    selectedPrice: { type: Number, min: 0 },
    totalAmount: {
      type: Number,
      required: [true, 'Total amount is required'],
      min: 0,
    },

    status: {
      type: String,
      enum: ['Pending', 'Confirmed', 'Cancelled'],
      default: 'Pending',
    },
    bookingId: {
      type: String,
      unique: true,
      required: false, // auto-generated by pre-save hook
    },
  },
  { timestamps: true }
);

// Indexes
agentBookingSchema.index({ status: 1, createdAt: -1 });
agentBookingSchema.index({ agentTripId: 1 });
agentBookingSchema.index({ agentId: 1 });
agentBookingSchema.index({ email: 1 });
agentBookingSchema.index({ bookingId: 1 });

// Auto-generate bookingId (AB000001, AB000002, ...)
agentBookingSchema.pre('save', async function (next) {
  if (!this.bookingId) {
    const count = await mongoose.model('AgentBooking').countDocuments();
    this.bookingId = `AB${String(count + 1).padStart(6, '0')}`;
  }
  next();
});

const AgentBooking = mongoose.model<IAgentBooking>('AgentBooking', agentBookingSchema);
export default AgentBooking;