// controllers/booking.controller.ts - COMPLETE FIX
import { Request, Response, NextFunction } from 'express';
import { catchAsync } from '../utils/catchAsync';
import { AppError } from '../utils/appError';
import Booking from '../models/Booking.model';
import Trip from '../models/Trip.model';

// @desc    Create new booking
// @route   POST /api/v1/bookings
// @access  Public
export const createBooking = catchAsync(
  async (req: Request, res: Response, next: NextFunction) => {
    const { 
      tripId, 
      tripName, 
      customerName, 
      email, 
      phone, 
      message, 
      travelers, 
      selectedDate, 
      selectedPrice, 
      totalAmount 
    } = req.body;

    // Validate required fields
    if (!tripId || !tripName || !customerName || !email || !phone || !travelers || totalAmount === undefined) {
      return next(new AppError('Please provide all required fields', 400));
    }

    // Verify trip exists
    const trip = await Trip.findById(tripId);
    if (!trip) {
      return next(new AppError('Trip not found', 404));
    }

    // Create booking - bookingId will be auto-generated by pre-save hook
    const booking = await Booking.create({
      tripId,
      tripName,
      customerName,
      email,
      phone,
      message: message || '',
      travelers,
      selectedDate: selectedDate || '',
      selectedPrice: selectedPrice || trip.price,
      totalAmount,
      status: 'Pending',
      // bookingId is NOT included - it will be auto-generated
    });

    // REMOVED: trip.bookings increment - was causing 500 error
    // If you need this feature, add 'bookings' field to Trip model first

    res.status(201).json({
      status: 'success',
      message: 'Booking request submitted successfully. We will contact you soon.',
      data: {
        booking,
      },
    });
  }
);

// @desc    Get all bookings
// @route   GET /api/v1/bookings
// @access  Private (Admin)
export const getAllBookings = catchAsync(
  async (req: Request, res: Response, next: NextFunction) => {
    const { status, search, page = 1, limit = 10 } = req.query;

    const query: any = {};

    // Filter by status
    if (status && status !== 'All') {
      query.status = status;
    }

    // Search functionality
    if (search) {
      query.$or = [
        { customerName: { $regex: search, $options: 'i' } },
        { email: { $regex: search, $options: 'i' } },
        { tripName: { $regex: search, $options: 'i' } },
        { bookingId: { $regex: search, $options: 'i' } },
        { phone: { $regex: search, $options: 'i' } },
      ];
    }

    const skip = (Number(page) - 1) * Number(limit);

    const bookings = await Booking.find(query)
      .populate('tripId', 'name destination duration image')
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(Number(limit));

    const total = await Booking.countDocuments(query);

    res.status(200).json({
      status: 'success',
      results: bookings.length,
      data: {
        bookings,
        pagination: {
          total,
          page: Number(page),
          pages: Math.ceil(total / Number(limit)),
        },
      },
    });
  }
);

// @desc    Get single booking
// @route   GET /api/v1/bookings/:id
// @access  Private (Admin)
export const getBooking = catchAsync(
  async (req: Request, res: Response, next: NextFunction) => {
    const booking = await Booking.findById(req.params.id).populate('tripId');

    if (!booking) {
      return next(new AppError('Booking not found', 404));
    }

    res.status(200).json({
      status: 'success',
      data: {
        booking,
      },
    });
  }
);

// @desc    Update booking status
// @route   PATCH /api/v1/bookings/:id
// @access  Private (Admin)
export const updateBooking = catchAsync(
  async (req: Request, res: Response, next: NextFunction) => {
    const { status } = req.body;

    if (!status) {
      return next(new AppError('Please provide status', 400));
    }

    const booking = await Booking.findByIdAndUpdate(
      req.params.id,
      { status },
      { new: true, runValidators: true }
    );

    if (!booking) {
      return next(new AppError('Booking not found', 404));
    }

    res.status(200).json({
      status: 'success',
      message: 'Booking updated successfully',
      data: {
        booking,
      },
    });
  }
);

// @desc    Delete booking
// @route   DELETE /api/v1/bookings/:id
// @access  Private (Admin)
export const deleteBooking = catchAsync(
  async (req: Request, res: Response, next: NextFunction) => {
    const booking = await Booking.findById(req.params.id);

    if (!booking) {
      return next(new AppError('Booking not found', 404));
    }

    await booking.deleteOne();

    res.status(200).json({
      status: 'success',
      message: 'Booking deleted successfully',
    });
  }
);

// @desc    Get booking statistics
// @route   GET /api/v1/bookings/admin/stats
// @access  Private (Admin)
export const getBookingStats = catchAsync(
  async (req: Request, res: Response, next: NextFunction) => {
    const totalBookings = await Booking.countDocuments();
    const confirmedBookings = await Booking.countDocuments({ status: 'Confirmed' });
    const pendingBookings = await Booking.countDocuments({ status: 'Pending' });
    const cancelledBookings = await Booking.countDocuments({ status: 'Cancelled' });

    const totalRevenue = await Booking.aggregate([
      { $match: { status: 'Confirmed' } },
      { $group: { _id: null, total: { $sum: '$totalAmount' } } },
    ]);

    const avgBookingValue = await Booking.aggregate([
      { $group: { _id: null, average: { $avg: '$totalAmount' } } },
    ]);

    res.status(200).json({
      status: 'success',
      data: {
        totalBookings,
        confirmedBookings,
        pendingBookings,
        cancelledBookings,
        totalRevenue: totalRevenue[0]?.total || 0,
        avgBookingValue: Math.round(avgBookingValue[0]?.average || 0),
      },
    });
  }
);